#:schema node_modules/wrangler/config-schema.json
name = "wasm-test"
main = "src/index.ts"
compatibility_date = "2024-11-27"
compatibility_flags = ["nodejs_compat"]

assets = { directory = "./public/" }
